defaults:
  - dataset: lapa
  - model: deeplabv3
  - optimizer: adam
  - trainer: trainer
  - scheduler: disabled
  - logger: wandb
  - callbacks: standard

  # To disable any .log files
  - hydra/job_logging: disabled
  - hydra/hydra_logging: disabled

hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: . # Set working dir to current directory
